In [4]:
import numpy as np
import math
a=500
print(np.exp(a))
print(math.exp(a))

1.4035922178528375e+217
1.4035922178528375e+217


In [7]:
def basic_sigmoid(x):
    s=1/(1+math.exp(-x))
    return s

In [8]:
basic_sigmoid(3)

0.9525741268224334

In [10]:
x=[1,2,3]
#basic_sigmoid(x)

In [12]:
x=np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [14]:
x=np.array([1,2,3])
print(x+3)

[4 5 6]


In [19]:
def sigmoid(x):
    """ compute the sigmoid of x
    
    arguments: X--  A sclar or numpy array
    
    of any size
    
    Returns s--sigmoid(x)"""
    s=1/(1+np.exp(x))
    return s

In [20]:
sigmoid(x)

array([0.26894142, 0.11920292, 0.04742587])